AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  RouteToRendered:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128a
      Timeout: 3
      Role: >-
        arn:aws:iam::984297430521:role/service-role/RouteToRendered-role-w3jf34sl
